name: Copy Container

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  copy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Skopeo
        run: sudo apt-get install -y skopeo

      - name: Copy Image
        run: bash test.sh
