name: clone container

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  clone:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: install skopeo
        run: sudo apt install -y skopeo

      - name: show version
        run: skopeo -v
