name: Copy Container

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  copy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Skopeo
        run: sudo apt install -y skopeo

      - name: Show Version
        run: skopeo -v

      - name: Show SystemVersion
        run: |
          cat /etc/os-release
          pwd
          ls .

      - name: copy nginx
        run: |
          bash test.sh
